### ISSUE TITLE
[New Effect] Stop time and peds

### ISSUE THREAD

**Issue by ShArCaDe** [gta-chaos-mod/Trilogy-ASI-Script#101]
When activated, the clock will stop and everyone - except CJ - will stand still/stop if they are in a vehicle. The player can interact with them (i.e. punching/killing them, stealing their vehicles) but they will not respond.

Cheat name: TimeStandsStill
Recommended length: 10/30 seconds

**Comment by Lordmau5** [comment]
I've added a variation of this effect in-dev already.

Maybe I'll come back to this specific idea later on but for now, a SUPERHOT style effect would probably be good enough.

**Comment by Lordmau5** [comment]
Added in v3.0.1
