### ISSUE TITLE
[New Effect] Lock vehicle camera

### ISSUE THREAD

**Issue by BZAnimations** [gta-chaos-mod/Trilogy-ASI-Script#104]
You know how in some racing games you can have a camera that will always stay behind the car and won't move unless you change the camera mode? Is it possible to add an effect that will lock the vehicle camera like that?

**Cheat code** : RaceCam
**Recomended lengths:**
**Easy** - 45 seconds
**Normal** - 60 seconds
**Hard** - 90 seconds
**Chaos** - 120 seconds

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
Added in v3.0.1, though needs more tweaking to allow rotation of the camera, too (Matrices are a pain to work with, I'm no math nerd)
