### ISSUE TITLE
[issue] The real "Pass current mission"

### ISSUE THREAD

**Issue by BZAnimations** [gta-chaos-mod/Trilogy-ASI-Script#105]
Ok so, there are 2 pass curent mission effects and one is fake, and one is real, right? Well, the fake one does it's job pretty well but the real one does not do anything at all. What i mean by that is not only does it not pass my current mission, it just doesn't have any affect at all. My mission just continues on like nothing. I tested to see if it really does not do anything by enabling only that in the chaos effects menu and it does nothing no matter how many times it gets chosen.

**Comment by YanN509** [comment]
Oddly, it seems to work if you disable widescreen. 
I don't know anything about C++, but I do know how to do a find & replace, and I'm gonna go on a whim here and say this code in PassCurrentMissionEffect.cpp might have some influence:
if (triedPassingMission || CCutsceneMgr::ms_running
        || FrontEndMenuManager.m_bWidescreenOn)
    {
        return;
    }

**Comment by bozata** [comment]
So you're saying that having widescreen enabled fucks with the effect and thus breaks it?

**Comment by YanN509** [comment]
> So you're saying that having widescreen enabled fucks with the effect and thus breaks it?

Basically, yes.

**Comment by Lordmau5** [comment]
Not related to this specific issue, but SA in general: The widescreen option isn't a *true* widescreen option. It just... stretches the game.
I'd much rather recommend using a proper widescreen mod and keeping that option turned off.

As for the check - if I remember correctly that particular boolean was also used in cutscenes where black bars appear on top and bottom, but the game isn't setting relevant variables in `CCutsceneMgr`.

If I find some time to work on this again I'll look into that. Maybe it *was* an oversight on my end and I grabbed the wrong variable after all.

**Comment by Parik27** [comment]
Yeah, that variable is supposed to be `TheCamera.m_bWidescreenOn` instead of `FrontEndMenuManager.m_bWidescreenOn`. The latter is the actual setting in the menu relating to the widescreen being enabled/disabled.

**Comment by Lordmau5** [comment]
Ah, so it was on me after all.
I pushed a commit that fixes it but can't say when I'll release a new version of the mod

**Comment by Lordmau5** [comment]
Should be fixed in v3.0.1
