### ISSUE TITLE
[New Effect] Low Render Distance

### ISSUE THREAD

**Issue by BZAnimations** [gta-chaos-mod/Trilogy-ASI-Script#109]
A timed effect that basically makes your render distance super low which mean that you can see the low poly models of buildings, cars and peds next to you and even see the world load in front of you

Lasting time: 50 seconds

**Comment by Lordmau5** [comment]
I've fiddled around a bit with some render distance and LOD stuff but couldn't get some good results.

If someone else would be interested they can do a pull request for this, which is why I will keep this issue open.
