### ISSUE TITLE
[BUG?] Those effects causing this weird bug: Mirrored World, Mirrored Screen, Upside Down Screen

### ISSUE THREAD

**Issue by Suxhe** [gta-chaos-mod/Trilogy-ASI-Script#110]
Whenever they are activated, my screen goes to this:
![S4JMnZw7yG](https://user-images.githubusercontent.com/4670602/100524607-2c34b400-31c2-11eb-94a0-883cb7ce6a19.png)

I have CLEO installed with Silent Patch

**Comment by bozata** [comment]
Yeah, disable those effects, i think the dev said they don't work with integrated gpu's and i think there was also something about AMD as well but i forgot. Just disable them and you'll be fine

**Comment by Lordmau5** [comment]
These effects only work if you have an NVIDIA GPU.
Integrated GPU (from either Intel or AMD) and dedicated AMD GPUs don't work with this effect.

The mod is open-source so if someone experience enough with that kinda stuff would like to take a look at it or even fix it then they're free to do so.
