### ISSUE TITLE
[Issue] Auto-Start isn't working

### ISSUE THREAD

**Issue by bozata** [gta-chaos-mod/Trilogy-ASI-Script#112]
The auto-start button on the chaos mod menu isn't doing anything and it just sits on "waiting..." the entire time, idk if it's from me or something but it just doesn't wanna turn on the mod while i'm in-game

**Comment by Lordmau5** [comment]
As explained in the long README that apparently not a single living soul reads:
> [...] press Auto-Start in the GUI, which will make it wait for you starting a new game and skipping the first cutscene (just like the autosplitter when doing a speedrun)

Meaning that it won't start on it's own when you're loading a save or just switch over back ingame

**Comment by bozata** [comment]
oh ok, i'm sorry then, i'm just an idiot
