### ISSUE TITLE
[New Effect] Swap vehicles on impact

### ISSUE THREAD

**Issue by Simon311** [gta-chaos-mod/Trilogy-ASI-Script#114]
The idea is to have a short-lasting effect, where colliding with any vehicle will force you into the driver seat of that vehicle, and force the AI driver (if there was one) into the driver seat of the vehicle you were driving.

**Comment by Simon311** [comment]
Is this going to be part of the mod? :o

**Comment by Lordmau5** [comment]
Yeah in v3.0 👀

**Comment by Simon311** [comment]
I sure hope Josh plays it 👀

**Comment by Lordmau5** [comment]
Added in v3.0.1
