### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Polarbite** [gta-chaos-mod/Trilogy-ASI-Script#119]
The game crashes after the trademarks screen after the intro when starting it up. 
I have Ultimate ASI Loader, NET Framework, and have extracted all of the files to my SA directory.
I'm running a 1.0 American version on Windows 10.
Any help?

**Comment by Lordmau5** [comment]
I'll be closing this for now since it's been over a year and the mod is getting a rewrite.
Chances are it'll work for you then, but I'm unsure.
