### ISSUE TITLE
Add sound in "to the left, to the right" effect

### ISSUE THREAD

**Issue by Djangoultra** [gta-chaos-mod/Trilogy-ASI-Script#126]
When the effect starts, the phrase "slide to the left, slide to the right" from cha cha slide https://www.youtube.com/watch?v=EWBLyKB9Ok8 sounds in the backround

**Comment by Lordmau5** [comment]
I will be looking into reworking how sounds are being played for effects in the 3.0 rewrite.

I *thought* I've already made it so users could put their own sound effects into a folder where the Chaos Mod GUI executable sits in (e.g. `audio/to_the_left_to_the_right.m4a` or similar) but apparently that's not implemented properly.

**Comment by Lordmau5** [comment]
v3.0.1 brought in a better way to override audio clips for every effect.
Upon first launch of the GUI it'll create a subfolder called `ChaosModAudio` with a readme. Please refer to this.
