### ISSUE TITLE
Game crashes mid loading screen

### ISSUE THREAD

**Issue by EugeneSzynka** [gta-chaos-mod/Trilogy-ASI-Script#128]
![Bez tytułu](https://user-images.githubusercontent.com/82712090/115114353-21bb6100-9f8f-11eb-8aee-842e65b8ec82.jpg)
Ive installed everything as said step by step, i launch the new game and it crashes in loading screen. I had the rainbomizer before and it worked well. Windows 10.

**Comment by EugeneSzynka** [comment]
great fkin response a year after i posted it xd

**Comment by Lordmau5** [comment]
I don't know if you're capable of reading what the main page said, but apparently you're not.
![image](https://user-images.githubusercontent.com/1345036/169402220-c12404d4-41fd-4043-802e-6083fc4cdaca.png)
![image](https://user-images.githubusercontent.com/1345036/169402240-60872db9-0882-4816-aadd-1d1b00e55fc8.png)

Anyway - No idea why it would crash mid loading screen, that crash is not indicative of anything.
Did you try it with a clean game? No other mods, just Chaos Mod?

Whatever the case may be, v3 is a rewrite from scratch that's currently in development and that might already fix that issue.
