### ISSUE TITLE
"Let's Take A Break" not working when game is played with a gamepad

### ISSUE THREAD

**Issue by matolog** [gta-chaos-mod/Trilogy-ASI-Script#13]
Saw on some random stream that with gamepad player still could move but couldn't sprint while "Let's take a break" effect was active.

**Comment by Lordmau5** [comment]
Currently `Lets Take A Break`, `Inverted Controls` and `Disable One Movement Key` all only work on keyboard.

I wanted to properly support gamepads as well, but haven't looked too much into it yet.

**Comment by Lordmau5** [comment]
Fixed in v2.2.0
