### ISSUE TITLE
Add New option in .exe program 

### ISSUE THREAD

**Issue by Djangoultra** [gta-chaos-mod/Trilogy-ASI-Script#131]
Add the option enable/disable "keep 'peds attacks each other/peds attacks you' effects activated during missions" in settings tab, please.

**Comment by Lordmau5** [comment]
Due to how the mod was written you had to explicitly set that option in the Chaos Mod config file (`<gta folder>/chaos_mod/config.toml`)

I'm not sure if I wanna keep it that way or if it's gonna be reworked with the 3.0 rewrite.

**Comment by Lordmau5** [comment]
After some more evaluation I've decided to actually remove the config option and force those effects off as they can cause irreparable damage to the save file.
