### ISSUE TITLE
[New Effect] Griefer Jesus

### ISSUE THREAD

**Issue by MrTongWah** [gta-chaos-mod/Trilogy-ASI-Script#136]
I am a huge fan of both chaos mods. I was thinking there could be a Griefer Jesus effect where it would spawn an enemy **with skin ID 72**, or model name "swmyhp1". This model looks like jesus with a blue plaid shirt, and have him have a 100% Accuracy Homing Launcher that shoots it at CJ, would be very hilarious as the Jesus character is a big meme within the SA 'Design Your Own Mission community'. Keep up the great work!

Cheat Code: **AndItWasJesus**
![Skinid72Jesus](https://user-images.githubusercontent.com/88998713/129510547-80e2a1d2-1d95-4f6f-9aa8-80499176f67b.jpg)

**Comment by Lordmau5** [comment]
There's a variation of this in the v3.0 rewrite already called `The Firing Circus` (a play of words on the Monty Python movie `The Flying Circus`)

It spawns 6 clowns around you that have 100% accuracy and have a very high chance of killing you.
Though, they despawn after 5 seconds, so there is a chance of survival.
