### ISSUE TITLE
"Health, Money & Armor" Cheat not setting armor to max armor the player has unlocked

### ISSUE THREAD

**Issue by Frouk3** [gta-chaos-mod/Trilogy-ASI-Script#139]
https://github.com/gta-chaos-mod/Trilogy-ASI-Script/blob/ff32ec055d6032aa80c5aba0d491383f55bfe32c/src/gtasa/effects/cheats/player/HealthArmorMoneyCheat.cpp#L21
This mistake is a huge, in original cheat it accessing max armor in player data (0xB7CD98+0x150)

**Comment by Lordmau5** [comment]
Why exactly are you making an issue with a title that doesn't even *try* to talk about what issue this is?

Anyway: Seems like an easy fix.
[CPlayerInfo.h#86](https://github.com/DK22Pac/plugin-sdk/blob/master/plugin_sa/game_sa/CPlayerInfo.h#L86) has a variable for the max armor so it's as simple as putting that in instead of 100.0f.

Will be fixing that once I will pick up development on the mod again (sometime in the near future probably)

**Comment by Frouk3** [comment]
> Why exactly are you making an issue with a title that doesn't even _try_ to talk about what issue this is?
> 
> Anyway: Seems like an easy fix. [CPlayerInfo.h#86](https://github.com/DK22Pac/plugin-sdk/blob/master/plugin_sa/game_sa/CPlayerInfo.h#L86) has a variable for the max armor so it's as simple as putting that in instead of 100.0f.
> 
> Will be fixing that once I will pick up development on the mod again (sometime in the near future probably)

I can do pull request so you can just merge

**Comment by Frouk3** [comment]
And ye i haven't enough time to think about title

**Comment by Frouk3** [comment]
Well that's great :D

**Comment by Lordmau5** [comment]
Nah, please keep this open so I can close it when it is actually fixed 😂
Better for me to keep track of things

**Comment by Frouk3** [comment]
ok

**Comment by Frouk3** [comment]
And one more thing that player using Cheat Engine can set max armor until the limit(255)

**Comment by Lordmau5** [comment]
As long as the value in `CPlayerInfo` is being updated it should work.

I will not go out of my way to support someone using Cheat Engine to alter it - not because you I want people to not *cheat*, but because it's something that's out of my control if they aren't doing it the right way

**Comment by Lordmau5** [comment]
Fixed in v3.0.1
