### ISSUE TITLE
[New effect] "Gun Game" (Replace Weapon On Kill)

### ISSUE THREAD

**Issue by fistopain** [gta-chaos-mod/Trilogy-ASI-Script#144]
I thought of "Gun Game". Like you kill a person and then get an other weapon, not necessarily a better weapon, but a different. Like weapon roulette, but it only changes if you kill someone.

**Comment by SpeedyFolf** [comment]
Drops from dead pedestrians is part of pickup randomizer in Rainbomizer.

**Comment by fistopain** [comment]
Yea but can still keep the old weapon. And i mean this as an effect for chaos mod, not Rainbowmizer.

**Comment by Lordmau5** [comment]
Hmm sounds like a fun effect indeed, should be easily doable.

So at the start it stores all the weapons you had so it can restore them later on.
Then it removes all the weapons and gives you a random one. (It also ensures you have it in case you die or get it taken away or similar)
When you kill someone it will replace it with a different one.
Once the effect is over, it will give you your previous weapons back.

Does that sound like what you had in mind?

**Comment by Lordmau5** [comment]
Added in v3.0.1
