### ISSUE TITLE
[New effect] "Low Distance"

### ISSUE THREAD

**Issue by Mrgtagamer** [gta-chaos-mod/Trilogy-ASI-Script#147]
![2](https://user-images.githubusercontent.com/108076004/175320375-e0a5240c-2e95-4d75-a5f9-20a3ebe49900.jpg)

![3](https://user-images.githubusercontent.com/108076004/175320486-a575ba5b-60c1-47e7-92f3-70243cc415f6.jpg)

**Comment by Mrgtagamer** [comment]
Super Low Draw Distance lol.
P:S: I'm using mod CLEO drawing

**Comment by Lordmau5** [comment]
I've tried this before but couldn't get it working properly - could you link me the CLEO mod so I could have a look at how it's doing this? :)

**Comment by Mrgtagamer** [comment]
CLEO Drawing link - https://drive.google.com/file/d/1An_IAxzsY0V53Ls3QCqgaijbMuMV2o7a/view?usp=sharing 
Controls: Ctrl+1 to increase the distance, Ctrl+2 to reduce the drawing distance.

**Comment by Mrgtagamer** [comment]
> I've tried this before but couldn't get it working properly - could you link me the CLEO mod so I could have a look at how it's doing this? :)

CLEO Drawing link - https://drive.google.com/file/d/1An_IAxzsY0V53Ls3QCqgaijbMuMV2o7a/view?usp=sharing
Controls: Ctrl+1 to increase the distance, Ctrl+2 to reduce the drawing distance.

**Comment by Lordmau5** [comment]
Okay so I tried decompiling it with Sanny Builder but wasn't able to get a good result of code to read.

While I'd really like to add this as an effect, if I don't know *how* to make it then I can't easily add it haha...

**Comment by Mrgtagamer** [comment]
When will version 3.0 be released?

**Comment by gromchek** [comment]
I think we need dig into the `CTimeCycle` class. There is field `m_fFarClip` that handle the draw distance.
If you change value:
```
//on start
farClip = CTimeCycle::m_CurrentColours.m_fFarClip * 0.05f;

//on tick
CTimeCycle::m_CurrentColours.m_fFarClip = farClip;
```
It does that we need, but looks weird sometimes.
