### ISSUE TITLE
(New effect) Autopilot

### ISSUE THREAD

**Issue by Mrgtagamer** [gta-chaos-mod/Trilogy-ASI-Script#153]
This effect makes your car go somewhere by itself, as an example on a marker on the radar, or on Mission objective
![Безымянный](https://user-images.githubusercontent.com/108076004/177427794-e1078a8a-1a0b-4cdf-8663-6e291ca74a2f.png)

**Comment by Mrgtagamer** [comment]
Also, during the action of this effect, you can not get out of the car /motorcycle

**Comment by Lordmau5** [comment]
Already implemented in some form, called `Drive Wander`.

**Comment by Mrgtagamer** [comment]
> Already implemented in some form, called `Drive Wander`.

It's in version v3.0?

**Comment by Lordmau5** [comment]
I've literally had it happen a couple of times on my dev streams, yes
