### ISSUE TITLE
MirrorWorld - radar shifts to screen "center".

### ISSUE THREAD

**Issue by r3538987** [gta-chaos-mod/Trilogy-ASI-Script#158]
GTA SA 1.0 US. 
Mod Version V2.3.4
NVIDIA RTX 2070S, as this effect I heard is GPU dependent. 

Here is result how it look like on mine machine. 
With widescreen fix by ThirteenAG and without. 
Only MirrorWorld is enabled. 
![image](https://user-images.githubusercontent.com/33725345/182648697-8f1fc018-d5da-4f92-93c8-74f59e037a17.png)

Any suggestion why radar gets shifted in such way?

**Comment by Lordmau5** [comment]
Fixed in 3.0, once I'll be able to release that.
