### ISSUE TITLE
Is the 3.0 branch up to date?

### ISSUE THREAD

**Issue by dex3r** [gta-chaos-mod/Trilogy-ASI-Script#159]
While watching the #ESASummer22 run (great job, 4h of fun) I noticed you @Lordmau5 said the new 3.0 version will be open sourced. Is the `3.0` branch it? Is it up to date? Looking at the source code I don't think it is?

If not, would it be safe for me to try to develop something there or the new-new version has major architecture changes? 

Also, please push the latest code to the public 3.0 branch when possible <3

Thanks and great job! Watching GTA chaos mod runs is easily the best stress relief after a hard day.

**Comment by Lordmau5** [comment]
3.0 branch is SEVERELY outdated and I am not sure when I'll be able to push all the new code.

I'd recommend waiting until it is and then looking at the new CONTRIBUTING.md that'll be coming in with it.

If I don't forget I'll try to respond to this issue again once it is :)

**Comment by Lordmau5** [comment]
It's up to date now :)
