### ISSUE TITLE
An Issue with Auto-save after missions

### ISSUE THREAD

**Issue by Twig2022** [gta-chaos-mod/Trilogy-ASI-Script#166]
When i finish a mission at the bottom right it says "Autosave complete" , i opened the load menu but i couldn't find the save file that the mod saved i passed alot of missions but the game ( mod ) still doesn't save anything ! Can anyone try to help out?
 
Thanks

**Comment by Lordmau5** [comment]
The "Load Game" option changes to "Load Autosave" when you are in that menu and hold Left CTRL

**Comment by Twig2022** [comment]
> The "Load Game" option changes to "Load Autosave" when you are in that menu and hold Left CTRL

ohhhhh shit i didn't know about that! 

sorry for posting a whole issue for a small dumbass question my bad

**Comment by Lordmau5** [comment]
Don't worry! It's not really mentioned anywhere so I should probably add it to the readme haha :D

**Comment by Lordmau5** [comment]
Oh wait, no, it's mentioned in the readme already, I guess I'm blind myself! 😂
![image](https://user-images.githubusercontent.com/1345036/189684428-6b921e92-2933-42c5-8bc5-2f970be7022d.png)

**Comment by Twig2022** [comment]
> Oh wait, no, it's mentioned in the readme already, I guess I'm blind myself! joy ![image](https://user-images.githubusercontent.com/1345036/189684428-6b921e92-2933-42c5-8bc5-2f970be7022d.png)

nah i'm the blind one :joy: didn't read the readme part i only read the instructions and started installing the mod 

what about adding a readme file in the zip folder so no one can think it's a bug namd post a whole like i did?

**Comment by Lordmau5** [comment]
Probably doesn't hurt, I'll consider it for the next version!

But there'll definitely be people that won't even read *that*. Plus, I feel all I'd put in there is a small text and a link to the main page telling people to read through it
