### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by closeone7** [gta-chaos-mod/Trilogy-ASI-Script#167]
Hi, i have installed chaos mode v.3.0.1 and when i press New Game it just crashes. I have Windows 11 with NET Framework 4.7.2 installed and gta_sa US 1.0. 
[crashdump.zip](https://github.com/gta-chaos-mod/Trilogy-ASI-Script/files/9610390/crashdump.zip)

**Comment by closeone7** [comment]
i tried 2.3.4 version and it works, that's strange, but i still want to play the 3.0.1 :D

**Comment by Lordmau5** [comment]
I've looked at the crash report but I couldn't spot anything weird with it...

When you first launched the game with 3.0.1 did it prompt you with the Windows Firewall about some network connection from GTA? If so, did you allow that? This is important since the mod opens up a small websocket server to allow the data to go from the UI to the game (and vice-versa)

Did you also try running GTA as admin?

**Comment by closeone7** [comment]
It didn't prompt me with anything, no firewall popup or something. I tried running GTA as admin but it doesn't work.

**Comment by Lordmau5** [comment]
I know I'm a bit late to this but if you are still having issues, could you try with this downgrader instead?
https://gtaforums.com/topic/927016-san-andreas-downgrader/

Someone ran into similar problems with the downgrader that's currently linked in the README in #181 and they said that downgrader worked perfectly

**Comment by closeone7** [comment]
Alright, i will try, i will be back later with a response

**Comment by closeone7** [comment]
When i try to scan, it just show me this: 
![image](https://user-images.githubusercontent.com/114020429/210082192-1bd107a7-2a6a-4c40-a22a-3e19dd1d23de.png)

**Comment by Lordmau5** [comment]
Hmm... it does say "Game Version - Retail v1 - Hood" which is, I assume, the correct version.

Can you perhaps try to remove the `gta_sa.set` file in your `Documents\GTA San Andreas User Files` folder?

**Comment by closeone7** [comment]
I have tried that, game still crashes

**Comment by closeone7** [comment]
The point is, i found that this downgrader doesn't work with this version, maybe that's why it's not scanning anything

**Comment by closeone7** [comment]
I really don't know what should i do

**Comment by Lordmau5** [comment]
You can try finding a 1.0 version of the game on [archive.org](https://archive.org/), seeing as you can't buy the original games anymore so I consider them abandonware in my book.

There are versions with around 1.7m and 800k views respectively, you could try with that - They should come with the no-cd patch from Hoodlum

**Comment by closeone7** [comment]
Can you help me with a link, if you don't mind, i can't find the versions with 1.7m and 800k views..

**Comment by closeone7** [comment]
I found a version with 800k views but it doesn't work..

**Comment by closeone7** [comment]
The thing is, i got the patch from hoodlum from the first time, and it didn't work with that also

**Comment by Lordmau5** [comment]
Do you have Discord? Might be easier to help you that way - Lordmau5#0001

**Comment by closeone7** [comment]
yeah, i'll add you

**Comment by Lordmau5** [comment]
Issue turned out to be related to the Intel Graphics Command Center using port 9001 and there not being a user-facing error about the port being in use.

Resolved in v3.1.2 by using different default ports.
