### ISSUE TITLE
(Bug) 

### ISSUE THREAD

**Issue by whywrongis** [gta-chaos-mod/Trilogy-ASI-Script#171]
After completing the T-Bone Mendez mission, I was teleported to los santos Airport, and I can no longer save, but it's good that I did save earlier, but I had to re-complete the missions of Jizzy and T-Bone Mendez.

**Comment by whywrongis** [comment]
There is no save icon anywhere else and it is not a Disable Hud, and I tried to remove the mod

**Comment by Lordmau5** [comment]
What do you mean "after completing the T-Bone Mendez mission"?

Did you get the "Pass Current Mission" effect while you were on that mission?

**Comment by whywrongis** [comment]
What do you mean "after completing the T-Bone Mendez mission"?

When I completed [this mission](https://youtu.be/ldLuQRk0Ny8), I was teleported to los Santos and all the save icons disappeared
![Безымянный](https://user-images.githubusercontent.com/112773774/192604106-90ae0599-3707-4cad-892f-3966acd9d72f.jpg)

![2](https://user-images.githubusercontent.com/112773774/192604353-b1697f64-5ab1-4317-848a-2f1a7209bd12.jpg)



Did you get the "Pass Current Mission" effect while you were on that mission?

No

**Comment by whywrongis** [comment]
I'm closing this because I have gta sa with more than 40 mods, so it's possible that this is not a Chaos Mod bug

And do you like the [effects](https://github.com/gta-chaos-mod/Trilogy-ASI-Script/issues/170) I came up with
