### ISSUE TITLE
Blips problem

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/Trilogy-ASI-Script#172]
![image](https://user-images.githubusercontent.com/78137181/193456572-14db6e84-1aee-40d2-8754-08e0ff5ec36b.png)
2 weird white squared blips, and shuffling or adding blips makes mission markers invisible (example: enemy Hydras or Ships in Vertical Bird mission)

**Comment by Lordmau5** [comment]
Okay so:

## White squared blips
~~I'm just iterating over all possible sprites that are available for blips. I assume that specific one I should skip, will do some testing in a bit.~~

Alright, this one's fixed in dev :)

## Invisible mission markers
Will have to see if I can maybe exclude those somehow... but chances are that I might not be able to.
Do they "return to normal" if you restart the mission?

**Comment by Lordmau5** [comment]
Due to a lack of reply on here I'll assume the 2nd report is a non-issue anymore and I consider this fixed in-dev as a whole.

**Comment by Kristof-30** [comment]
> Okay so:
> 
> ## White squared blips
> ~I'm just iterating over all possible sprites that are available for blips. I assume that specific one I should skip, will do some testing in a bit.~
> 
> Alright, this one's fixed in dev :)
> 
> ## Invisible mission markers
> Will have to see if I can maybe exclude those somehow... but chances are that I might not be able to. Do they "return to normal" if you restart the mission?

They DON'T, they're always invisible

**Comment by Jersukai** [comment]
The number of blips that can be saved in the save file is limited to 175. If you have too many no new blips can be created. This can softlock missions too.

As a solution you can limit add random blips 170 or so. Or delete all the blips when full.

**Comment by Kristof-30** [comment]
Yeah this softlocks 1 of Catalina's missions (with quadbikes) and Breaking The Bank At Caligula's

But I don't think you can set some limits, unless in game code which I don't know how to hack into.

**Comment by Lordmau5** [comment]
> The number of blips that can be saved in the save file is limited to 175. If you have too many no new blips can be created. This can softlock missions too.
> 
> As a solution you can limit add random blips 170 or so. Or delete all the blips when full.

It's been lowered to adding a random amount between 1 and 3 instead of 5 and 10 so if you run into that limit then consider disabling the effect.
I've tried removing blips that were added but it just ended up crashing the game. Might revisit it in the future, for now it's not of any priority.
