### ISSUE TITLE
Setting up a Sync Server

### ISSUE THREAD

**Issue by Saymite** [gta-chaos-mod/Trilogy-ASI-Script#173]
I was hoping to do a small race with one or two friends but I can't seem to find a way to setup a sync server.

On the UI, I only see exposed the options to connect, I tried digging around some files from both the mod and complementaries but found nothing.

![image](https://user-images.githubusercontent.com/13812950/194730488-bc2ca24a-aef1-4cf3-a3b3-c5d9518f6f46.png)

I've also tried searching both here and in google and found nothing.

Any help would be appreciated, sorry if it's literally in front of me I'm usually very blind with these things.

**Comment by Lordmau5** [comment]
The guide isn't linked on this repo but can be found here

https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/tree/v3.0/SyncServer.NodeJS

Please report back if you got it working this way :D

**Comment by Saymite** [comment]
Thank you! everything seems to be working fine.
I would ask that you maybe link to this guide in the readme, but that's up to you of course.

I'm sure people interested enough on hosting would find this issue by simply searching.

**Comment by Lordmau5** [comment]
I'll see that I get it added into the readme, yeah :)
