### ISSUE TITLE
no application

### ISSUE THREAD

**Issue by Fahdad1234** [gta-chaos-mod/Trilogy-ASI-Script#175]
when i download the zip file i dont have the .exe how do i fix this
[Trilogy-ASI-Script-3.0.zip](https://github.com/gta-chaos-mod/Trilogy-ASI-Script/files/9846962/Trilogy-ASI-Script-3.0.zip)

**Comment by Lordmau5** [comment]
You need to download it from the Releases tab (the 7z file) https://github.com/gta-chaos-mod/Trilogy-ASI-Script/releases
