### ISSUE TITLE
Something (inverted gravity) causing objects to shift

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#176]
Some non-solid objects get higher over time. This also includes their collisions and planted trees. Not sure if it's some of those object effects. This gets saved in save files.
![gallery932](https://user-images.githubusercontent.com/112782703/197599778-dbce3854-86d0-4a65-ada0-45cc1072ca92.jpg)
![gallery933](https://user-images.githubusercontent.com/112782703/197599798-7dacb51d-3e80-409e-9391-19fde428f255.jpg)
![gallery934](https://user-images.githubusercontent.com/112782703/197599808-d41e548c-a886-4a27-8541-b95850bac6fc.jpg)
![gallery935](https://user-images.githubusercontent.com/112782703/197599825-1bebdcb7-850f-458f-935e-463b669724ae.jpg)

**Comment by Lordmau5** [comment]
Had this happen during my last few sessions as well and, off the top of my head, I don't know what might be causing this...

I don't remember having any Object Scale / Rotation effects enabled so I doubt it's that...

**Comment by Lordmau5** [comment]
Could this be related to #168 that you opened as well?

**Comment by Lordmau5** [comment]
Another thing I noticed when you are being teleported out of an interior is that the radar will be zoomed in or in the wrong spot.

I've got a fix for that and it *might* fix the shifting objects as well, but I need you to check on that again (or I'll have to see if I notice anything from my end)

**Comment by Jersukai** [comment]
You have to play for many hours until you notice them shifted. I just tried several things: all object effects, teleports, leaving and coming back if it's the loading/unloading/LODs. But didn't get them to shift. 

Before reporting this I tried some effects and i think I got them shifted a bit.

In the race edition you had bug of LOD objects not resetting properly. Is its fix something that applied constantly or only when the effect ends? Can that fix have anything to do with this?

I keep testing and try to find the reproduction steps.

**Comment by Jersukai** [comment]
Inverted gravity

Their position doesn't get updated in real time. Fade is needed to refresh them

**Comment by Lordmau5** [comment]
Yeah I see why that'd be an issue:
```cpp
        for (CObject *object : CPools::ms_pObjectPool)
        {
            object->GetPosition ().z += 0.2f; // This one right here is the culprit
            object->m_vecMoveSpeed.z = 0;
        }
```

I'm effectively pushing every ped, vehicle and object up by 0.2f on the Z axis so they get a slight "lift-off". Means peds don't have to jump to go flying upwards.

I'll just remove objects from this for now, makes the most sense

Thank you for checking more into this!
