### ISSUE TITLE
Names showing up when they shouldn't

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#177]
When there's chat voted chaos and they vote for (hyper) rapid-fire. If there are effects that the chat has entered before, those effects have their name under them.

**Comment by Lordmau5** [comment]
The standalone effects "Rapid-Fire", "Hyper Rapid-Fire" and "Discount Rapid-Fire" are mostly desigend for offline play since some people requested getting multiple effects at once.

When one of these get's activated the effects they pick are completely random.

**Comment by Lordmau5** [comment]
How the hell did I completely misread what you said

Yeah I'll get that fixed, shouldn't be too difficult :D
