### ISSUE TITLE
Can't start a mission after "Outrider"

### ISSUE THREAD

**Issue by PhPmayan** [gta-chaos-mod/Trilogy-ASI-Script#178]
Hello, When I did the mission Outrider during the cutscene near the van and the sanchez, I had an actual pass current mission effect. And it still showed me that i'm in Outrider. So basically OM0. I decided to try to do it while i'm on OM0 to see if I can skip Snail Trail and sadly I can't start Snail trail or even progress, even though I have Woozie mission availlable but I will do this for nothing probably because I can't start snail trail.
By the way, I still have to Loco syndicate icon on the map and not the C.R.A.S.H icon. Am I just wrong and I have to just pass the first Woozie missions or i'm kind of softlocked? or I can even use an older autosave if that's even possible
Thanks for the help

**Comment by Lordmau5** [comment]
You should be able to load an older autosave - they are in the `Documents\GTA San Andreas User Files\chaos_mod` folder, indexed by the amount of missions you completed at that time

I'll look into it in the coming days, maybe Outrider has a wrong offset or something similar.

Just making sure - you are on 3.0.1 though, right?

**Comment by PhPmayan** [comment]
> You should be able to load an older autosave - they are in the `Documents\GTA San Andreas User Files\chaos_mod` folder, indexed by the amount of missions you completed at that time
> 
> I'll look into it in the coming days, maybe Outrider has a wrong offset or something similar.
> 
> Just making sure - you are on 3.0.1 though, right?

you mean the version of the chaos mod? so yes

**Comment by PhPmayan** [comment]
Also how can I load an older autosave? I don't mind doing outrider again

**Comment by Lordmau5** [comment]
Rename one of the `chaos_autosave.mission_NUMBER.b` files to just `chaos_autosave.b` - or to `GTASAsf1.sf` to `8.sf` in the folder outside of that (where the `gta_sa.set` file is) for the manual "Load Game" saves

**Comment by PhPmayan** [comment]
> s

yes it worked! Thanks a lot lordmau
