### ISSUE TITLE
Game not starting after copying in chaos mod files

### ISSUE THREAD

**Issue by MarkUeberall** [gta-chaos-mod/Trilogy-ASI-Script#181]
I've downgraded my game, installed the ultimate asi loader and silent patch without issues. However, after copying the chaos mod into the SA folder the game (gta-sa.exe) won't not start anymore and doesn't give any crash or error message. It actually shows up in task manager for a split second along with a windows problem reporting process before both disappear. I've included the info from the event viewer at the end in case that's of any help.  

After deleting the chaos mod files the game starts up again as normal. I've also already tried to do a fresh install of the game and mods but the problem persists.

![general](https://user-images.githubusercontent.com/54077680/209982512-717db8fb-9a98-4d3a-bd12-a48905b12048.png)
![details](https://user-images.githubusercontent.com/54077680/209982565-718c4626-4d38-4b8c-84eb-a5d2f74e2d67.png)

**Comment by Lordmau5** [comment]
I'd assume you have downgraded properly as well, meaning your `gta-sa.exe` should be around 14MB in size, correct?

What helped someone else before is to go to your GTA San Andreas User Files in your Documents folder and deleting the `gta_sa.set` file.

**Comment by MarkUeberall** [comment]
You're right, the downgraders from the Forum thread apparently didn't work right for me. The downgrader by gamerzworld worked fine and the rest of the installation went through without a hitch. 

Sorry, I should've looked around more before opening an issue but maybe someone runs into the same problems. Thank you for taking the time and have a happy new year.

**Comment by Lordmau5** [comment]
I'll get the README updated with that downgrader in that case, glad it works now! :)

And wishing you a happy new year, too!
