### ISSUE TITLE
ATTENTION, ALL GAMERS! RAPID-FIRE HAS BEGUN! VALID EFFECTS WILL BE ENABLED FOR 15 SECONDS!

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#183]
The timer is only 10 seconds

**Comment by Jersukai** [comment]
Unless that means that the length of the effects is 15 seconds then that's correct

**Comment by Lordmau5** [comment]
Yeah, you are correct and I was too fast on adding the labels lmao

Rapid-Fire with Twitch **lasts** for 10 seconds and all effects that get sent over are running **for** 15 seconds
