### ISSUE TITLE
Link sound effects to fake teleport

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#185]
Make fake teleport use the same sound effects as the real teleport if it doesn't have a sound effect specified

**Comment by Lordmau5** [comment]
Just put the same sound as any of the other teleports in as an override in the ChaosModAudio folder.

**Comment by Jersukai** [comment]
I have put different sound effects for the real teleports. Are you saying there is a way to make the fake teleport use them? I just don't want the lack of sound effect to give it away it was a fake.

**Comment by Lordmau5** [comment]
You can just use the same sound effect for the Fake Teleport effect, yes. Just copy the audio and rename it to whatever it needs to be called for the Fake Teleport effect
