### ISSUE TITLE
Vehicle weapons and related effects

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#187]
You can still use vehicle weapons (Hunter for example) with No shooting allowed.

Disable shooting only disables primary fire.

**Comment by Jersukai** [comment]
Cool! I didn't expect you to add these labels so soon. There may be more things to consider.

Explosive bullets don't work

Recoil? Do kickflips whenever you want with Rhino!

Is firefighter mission illegal now?

**Comment by Lordmau5** [comment]
> Explosive bullets don't work

Dunno what you mean with this

> Recoil? Do kickflips whenever you want with Rhino!

?

> Is firefighter mission illegal now?

Probably? Don't care

**Comment by Jersukai** [comment]
Still talking about vehicle weapons and effects related to shooting.

Yeah the recoil doesn't have to work for vehicles. That was a joke

**Comment by Lordmau5** [comment]
Ah I see

Yeah the moment you shoot in a Rhino you'd just die

You're probably also gonna die in a firetruck because of this. But it's still considered shooting so yknow :P
