### ISSUE TITLE
[New effect] Teleport to negated coordinates

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#201]
X and Y are negated.

**Comment by Lordmau5** [comment]
I honestly don't think it's as good as effect as you might think...

Like, yeah the map easily allows just inverting the coords since it ranges from -3000,-3000 to 3000,3000 but... isn't this just more or less Random Teleport?

**Comment by Jersukai** [comment]
Semi-random. It's consistent if you get it multiple times in the same area. This usually teleports you very far, to other side of the map. I get you don't want too similar effects. We get less teleport now that there're much more effects so I thought suggesting a few more, not fixed but different. I thought you would prefer the other one since that one won't teleport you far.

**Comment by Lordmau5** [comment]
Yeah there aren't many teleports, and I've also only included like 4 teleports into the WIP Crowd Control support (which I still think is a bit too much but that's a different story)

The thing nowadays with Chaos Mod is that it's going through ALL effects at random through some sort of bucket.
An effect happens, it get's removed from the bucket. When the bucket is empty, all effects get added to it again.

So if you're very unlucky, you could have all other effects happen first and THEN you get all teleports in a row.
___
But back to the effect itself - again, I don't think it'd be that good of an effect personally
