### ISSUE TITLE
[New effect] Traffic Is Random Vehicle

### ISSUE THREAD

**Issue by Thisis2023** [gta-chaos-mod/Trilogy-ASI-Script#203]
Replaces all traffic with any random transport

In the game it will be called: Traffic Is (Name of the transport)

**Comment by Thisis2023** [comment]
I also think that this effect does not need to include Planes, Helicopters and Boats

**Comment by Lordmau5** [comment]
There are already several "Traffic Is ..." effects that I've hand-picked because I didn't think having **all** vehicles in the game available for that would be a good idea.

It's also a bit held back by issue #182 unfortunately...

If I were to add a "Traffic Is Random Vehicle" (or rather, it'd replace the vehicle name ingame then) it'd still be a handpicked list of vehicles. Would that be okay?

**Comment by Thisis2023** [comment]
> There are already several "Traffic Is ..." effects that I've hand-picked because I didn't think having **all** vehicles in the game available for that would be a good idea.
> 
> It's also a bit held back by issue #182 unfortunately...
> 
> If I were to add a "Traffic Is Random Vehicle" (or rather, it'd replace the vehicle name ingame then) it'd still be a handpicked list of vehicles. Would that be okay?

I mean, traffic can be any car or motorcycle, but not a boat, plane or helicopter

**Comment by Lordmau5** [comment]
And I repeat, would you be okay with a handpicked list of cars or motorcycles because I wouldn't allow **every** vehicle

**Comment by Thisis2023** [comment]
> And I repeat, would you be okay with a handpicked list of cars or motorcycles because I wouldn't allow **every** vehicle

Yes, I want this effect to be in the game

**Comment by Thisis2023** [comment]
> And I repeat, would you be okay with a handpicked list of cars or motorcycles because I wouldn't allow **every** vehicle

Also, is it possible to make an effect that will change your current transport to any random one, but in missions this can lead to fail

**Comment by Lordmau5** [comment]
> > And I repeat, would you be okay with a handpicked list of cars or motorcycles because I wouldn't allow **every** vehicle
> 
> Also, is it possible to make an effect that will change your current transport to any random one, but in missions this can lead to fail

It is possible, yes. But I don't want to do this until I can find a way to reliably change mission vehicles as well, which requires messing with the game's memory and potentially causing crashes, so for now that's not enabled.

**Comment by Lordmau5** [comment]
Added in v3.1.3
