### ISSUE TITLE
UI scale setting

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#204]
So used to the old UI that the new UI looks a bit small now. Adding a scale setting shouldn't be too hard?

**Comment by Lordmau5** [comment]
Adding a scale setting is too hard actually.

**Comment by Lordmau5** [comment]
To actually, properly elaborate on this:
Most of the values for drawing the effects are kinda static and I had to calculate the offset and such by hand to make the timer vertically centered, for example.

I feel this is mostly a "being used to the old UI scale" issue and not a "I LITERALLY CANNOT READ ANYTHING" issue, correct?

Granted, I've stopped giving a shit about people that play on 800x600 in the year 2023.
To those that are playing on such a resolution: Chances are that your PC can't even properly handle the Chaos Mod on it's own.

**Comment by Jersukai** [comment]
Yeah, mostly. 1920 x 1080 laptop
