### ISSUE TITLE
New UI bugs

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#205]
Hide chaos UI hides itself too

Disable HUD hides effects too

Black HUD effects hide every effect behind except the top one:
![DVD chaos bugi](https://user-images.githubusercontent.com/112782703/211162028-14b0f8c4-8463-4652-9d51-d5efa4c923b9.png)

**Comment by Lordmau5** [comment]
I've reverted back to the old drawing method (literally on top of everything) and have implemented the lower-opacity-if-a-menu-is-open logic for Timed Effects (on the left) as well.

**Comment by Lordmau5** [comment]
Fixed in v3.1.3
