### ISSUE TITLE
Get to the Marker‽

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#219]
Are you even keeping this effect. The timer is supposed to be 5 minutes? Right now it's only 1 cooldown

**Comment by Lordmau5** [comment]
That's already fixed in-dev - it was supposed to be 5mins like in the Crowd Control implementation

**Comment by Jersukai** [comment]
I thought you may be removing it since it's not in the spreadsheet anymore

**Comment by Lordmau5** [comment]
Could very well be that I never added it to the spreadsheet - it's difficult keeping that thing properly up-to date

**Comment by Lordmau5** [comment]
Fixed in v3.2.0

**Comment by Jersukai** [comment]
You sure you fixed this?

**Comment by Lordmau5** [comment]
Hmm, seems like this affects not just this effect but others as well.

The logic for duration overrides seems a bit messed up, I'll get that fixed

Alright it's fixed in the newest commit on the GUI, gonna see that I'll publish a 3.2.1 tomorrow
