### ISSUE TITLE
Fake teleport crash

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#223]
Fake teleport (or Liberty City) can crash if it happens when you're in an interior and when it's about to teleport you back. Something to do with #168? I don't remember it crashing before that fix.

I think I have got some real teleports cause crashes too. I don't remember if they were from interiors or not

[CrashDumps.zip](https://github.com/gta-chaos-mod/Trilogy-ASI-Script/files/10459579/CrashDumps.zip)

**Comment by Lordmau5** [comment]
I do have one guess that it might be related to me setting this here https://github.com/gta-chaos-mod/Trilogy-ASI-Script/blob/3.0/src/gtasa/util/Teleportation.cpp#L56

But I can also see some CLEO related calls in the logs so I'm not sure if they are doing something wrong there themselves.

I think I might have to reset that to 0, let me push a fix for that

**Comment by Lordmau5** [comment]
Alright, pushed. Once https://github.com/gta-chaos-mod/Trilogy-ASI-Script/actions/runs/3987433670 is built you should be able to download the SA ASI from that and then you can try reproducing it

**Comment by Jersukai** [comment]
No crashes so far
