### ISSUE TITLE
ERROR 126

### ISSUE THREAD

**Issue by imsiby** [gta-chaos-mod/Trilogy-ASI-Script#225]
I watched 1000 tutorials to run the chaos mod, I downloaded absolutely everything, deactivated the antivirus, downloaded version 1.0 of GTA SA, I LITERALLY DID EVERYTHING!!! AND IT DOES NOT OPEN THE GAME, HELP!
![a](https://user-images.githubusercontent.com/123117004/213543439-2053321a-1e17-4d64-8a2c-94a2ecef3603.png)

**Comment by Lordmau5** [comment]
Oh crap, I forgot to add the `bass.dll` to the latest release, that's my bad.

I've updated the latest release, can you try downloading that again and seeing if the `bass.dll` is apart of it, and if so, please put that into the game folder, then trying to start the game again?

**Comment by Lordmau5** [comment]
I'm gonna assume that fixed it, and if it didn't make sure to install the DirectX 9 runtime that's linked in the readme as well
