### ISSUE TITLE
Experimental Youtube Feature Doesn't Work

### ISSUE THREAD

**Issue by Darkthus** [gta-chaos-mod/Trilogy-ASI-Script#231]
Hello,

I'm having issues with getting Chaos Mod to connect to my Youtube stream. What happens is that I copy the Stream key into the Access Token field (and write gibberish into Client ID, as instructed), and then when I press "Connect to Steam" it instantly throws up a message saying "There was an error trying to log into the account. Invalid Access Token?". OBS is able to connect to that stream key.

I have turned on the experimental option for youtube connectivity.

Maybe related, but if I were to connect it to twitch, it pauses for a second before throwing up the error message.

**Comment by Lordmau5** [comment]
It's not the stream key but the Livestream ID, as in the ID that's in `watch?v=<this_here>` if I remember correctly

**Comment by Lordmau5** [comment]
Yes, I just double-checked - it requires the Livestream / Video ID

```csharp
string streamURL = $"https://www.youtube.com/watch?v={this.liveId}";
```

As you can see here it builds the YouTube URL with that Live ID.

**HOWEVER:**
The Live ID seems to be the **Client ID** field. A bit confusing and I should *really* update the UI for this.

Can you try putting just the Live ID into the **Client ID** field and something gibberish into the Access Token field?

**Comment by Darkthus** [comment]
Holy heck, that did it! Thank you very much!

I thought the livestream ID was the stream key (thanks, Google). 

If it's not a problem to you, could you update the description of the mod regarding this feature, please (to make sure people use the Client ID field)?

Again, thank you and keep up the good work.

**Comment by Lordmau5** [comment]
Yep, I'll see if I can perhaps even update the text to indicate that

In theory I should be able to disable the other field, too, and maybe even allow just pasting in the whole YouTube live URL (as in, the one with `watch?v=...`)

I'll leave this issue open for now if that's cool with you?

**Comment by Darkthus** [comment]
Sorry for the late response - I'm cool with you leaving it open.

**Comment by Lordmau5** [comment]
Alright, would you mind trying it out with this build?
https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/suites/10878321695/artifacts/548895045

Should be a bit easier to setup and understand :)

Do note that YouTube support is still experimental as I don't really have the resources to heavily test it
