### ISSUE TITLE
Any custom texture effect uses the specified image to cover the entire screen rather than replacing textures.

### ISSUE THREAD

**Issue by dennalig** [gta-chaos-mod/Trilogy-ASI-Script#233]
Hello, I am running into an issue where any custom texture effect does not replace current textures but instead covers the screen with the specified image.

**Comment by Knuxfan24** [comment]
In my experience, this was caused by SkyGfx being enabled, something about how the texture replacement effects work seemed to conflict with it?

**Comment by Lordmau5** [comment]
It could be that SkyGfx is overlaying some texture on the screen as a whole - all I'm doing is replace all texture load hooks with a custom file, I don't really have fine-control with those effects.

Can you try removing mods 1-by-1 to figure out what causes this in case SkyGfx isn't at fault?

**Comment by dennalig** [comment]
Thank you! That Skygfx is exactly what it was!
