### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by FIXNeon** [gta-chaos-mod/Trilogy-ASI-Script#24]
It'll work about 10 seconds and you can't see, what's going on.

**Comment by Lordmau5** [comment]
I assume this is a suggestion for an effect? Just wanting to make sure :D

**Comment by FIXNeon** [comment]
Yes, an effect.

**Comment by Lordmau5** [comment]
Added in v3.0.1 (Used to have this in the past as "Woozie Mode", don't remember why I removed it)
