### ISSUE TITLE
Couldn't create websocket server on port 42069, Is it in use? how to fix this

### ISSUE THREAD

**Issue by iqbaldwiansyah** [gta-chaos-mod/Trilogy-ASI-Script#250]

**Comment by Lordmau5** [comment]
Please go to the Settings tab and change the Websocket Port on the bottom to something else, e.g. 42070, then hitting Restart Websocket, then seeing if it works.

If that still doesn't work, please try running it as an admin

**Comment by iqbaldwiansyah** [comment]
websocket fix but chaos not running , i already install net 4.75
![ccccccc](https://user-images.githubusercontent.com/82165626/231754783-38b9de16-89f9-44ec-baf1-586e4766ea51.png)

**Comment by Lordmau5** [comment]
If you change the websocket port in the ui, you also have to change the websocket port in the mod config

GTA folder/scripts/TrilogyChaosMod.SA.toml

**Comment by iqbaldwiansyah** [comment]
thanks , it work

**Comment by Lordmau5** [comment]
Glad to hear! I should add that to the README so people know they also need to change the mod config
