### ISSUE TITLE
my game crash

### ISSUE THREAD

**Issue by Suryyartz** [gta-chaos-mod/Trilogy-ASI-Script#263]
the mod and exe work but when any cutscenes start it just freez

**Comment by Suryyartz** [comment]
can some one help me?

**Comment by Lordmau5** [comment]
I know I'm over a year late to this but all I can suggest is to make sure you have downgraded your GTA:SA copy to 1.0 (or grab a 1.0 copy from somewhere)

The size of it should look like this in Windows Explorer
![image](https://github.com/user-attachments/assets/fd69d229-3869-4366-a410-46d85b0ee695)

And like this when you open its properties
![image](https://github.com/user-attachments/assets/69a60a9e-d9be-43a1-adbb-529a32c8ed5b)

**Comment by Suryyartz** [comment]
Lmao, yah it was downgraded tho, u just gave me interest to play the game again, even ur suggestion is already done before tho

**Comment by Lordmau5** [comment]
So do you still have the crashing issues with cutscenes?

If so, maybe it's incompatibilities with other mods (for example custom skins / models - I know of a streamer that has to turn off his custom character model before certain cutscenes even without the Chaos Mod)

Also as I said, maybe try a 1.0 ready version - I've heard of issues with downgraders not working properly
