### ISSUE TITLE
[New Effect] Russian Roulette

### ISSUE THREAD

**Issue by kamfretoz** [gta-chaos-mod/Trilogy-ASI-Script#275]
Constantly roll player's weapon at an interval like every 5 seconds (so that they can use it albeit briefly) until the effect runs out.
Timed effect.

**Comment by gromchek** [comment]
Mod already have an effect "Weapon Roulette"

**Comment by Lordmau5** [comment]
As gromchek said, this effect already exists as "Weapon Roulette"
