### ISSUE TITLE
[New Effect] The Ground Is Lava

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#28]
Self-explanatory. Everything that would be considered ground would quickly damage CJ. Riding a vehicle would make it catch fire **but** if an NPC is driving a vehicle, it does not catch fire and you can safely stand on it. Etc. On the hardest difficulty, water would act as lava and damage CJ too.

**Cheat Code name:** BurningEarth or VolcanicGround
**Recommanded lengths:**
**Easy:** 30 seconds
**Normal:** 60 seconds
**Hard:** 90 seconds
**Chaos:** 180 seconds + water is lava

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
Haven't found a good way to see if the player is actually touching the ground so I'll close this for now.
