### ISSUE TITLE
Effects only working outside on mission don't work.

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/Trilogy-ASI-Script#296]
Once you get NPC's Attack You, NPC's Attack Each Other or Bounty On Your Head it doesn't appear at all into the effect list. And it doesn't matter if you will get the effect in mission or outside of mission. This happens on the newest version released today (v3.2.1)

**Comment by Kristof-30** [comment]
Additionally I don't get why Misty Weather have so many effect groups, a lot of cooldown effects cancel it

**Comment by Lordmau5** [comment]
> Once you get NPC's Attack You, NPC's Attack Each Other or Bounty On Your Head it doesn't appear at all into the effect list. And it doesn't matter if you will get the effect in mission or outside of mission. This happens on the newest version released today (v3.2.1)

Judging by this commit I have removed them as a whole - did I forget to remove them from the GUI https://github.com/gta-chaos-mod/Trilogy-ASI-Script/commit/d6aac6914984e9b4ea228c0a07586de77fe14d46 

As for Misty Weather - yeah I just noticed that, too - I'll get a fix out later
