### ISSUE TITLE
Feedback for new effects

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/Trilogy-ASI-Script#298]
Give NPCs a weapon:
Weapons appear invisible if it's not loaded into memory

Coughing:
This got me softlocked in ammunation and I suspect this softlocks a lot of cutscenes too. Maybe don't allow coughing when player doesn't have control.

Auto collect pickups:
The range could be bit higher. To make it more annoying to avoid picking up something you don't want.

Acid rain:
Weather is not cleared/restored when effect ends.

**Comment by Lordmau5** [comment]
Coughing should be fixable with a "IsPlayerSafe" check or whatever method I had for it

**Comment by Lordmau5** [comment]
Auto collect pickups is gonna stay at the same range for now, the rest has been fixed
