### ISSUE TITLE
[New Effect] 180 degree CJ Flip

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#31]
180 degree flip's CJ's model which would make it seems like his head are his limbs. This is purely aesthetic; would not affect gameplay. Bonus: all pedestrians / NPC would be the same. With 180 screen flip, it would really seem like you are walking on air. lol.

**Cheat Code name:** WalkingOnAir
**Recommanded lengths:**
**Easy:** 150 seconds
**Normal:** 150 seconds
**Hard:** 150 seconds
**Chaos:** 150 seconds

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
Added in v3.0.1
