### ISSUE TITLE
[New effect] Cops Everywhere

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#35]
Self-explanatory. Makes it easier to rack up wanted stars and get busted for stealing a car (coz all pedestrians in cars are cops).

**Cheat Code name:** PoliceState
**Recommanded lengths:**
**Easy:** 45 seconds
**Normal:** 60 seconds
**Hard:** 90 seconds
**Chaos:** 180 seconds

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
Added in v3.0.1
