### ISSUE TITLE
[New effects] Teleport to the nearest *insert place here*

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#36]
Self-explanatory. However, those places are generic and not necessarily "hot spots".

A list of place we could teleport to:
* Gym (Code: YouNeedAWorkout)
* Police Station (Code: OutOfJail)
* Hospital (Code: Unwasted)
* Fire Department (Code: Fireman)
* House or establishment **for purchase** / house or establishment **already purchased** (Code: HomeForSaleNearYou) (Note: excludes Grove Street home)
*  Restaurant (Code: FastFood)

**Cheat Code name:** 1 for each place
**Recommanded lengths:**
**Easy:** N/A + 1-time effect
**Normal:** N/A + 1-time effect
**Hard:** N/A + 1-time effect
**Chaos:** N/A + 1-time effect

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
Actually... I just thought of something.

This could be handled by a list of static positions for each location (all gym locations, all police station locations, ...) and then calculating the position of the player distance to those.
