### ISSUE TITLE
[New effect] Reverse Paint n Spray (invisible effect)

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#37]
Paint n Spray gives you 2 additional stars instead of removing them. If stars are already maxed out, player is busted. In chaos, player is busted regardless of wanted level. This effect would be stealthily introduced along with another cheat for the sake of surprise. When the effect is dicovered, it shows up with the list of effects. The duration, on all difficulties, is 10 minutes for having a chance of tricking the player. When player finds out, the duration is set to 1 minute on easy and normal. On hard and chaos, because you get busted, the effect just ends. Because the effect starts hidden, this is the rarest effect: when a cheat is selected, there's a 1% chance of activating this one too. 

For the laughs, custom text should be implemented too!

On easy and normal (adds 2 stars): "Oh no! The owner called the cops on you! Hurry, get out and hide!"
On hard and chaos (insta-busted): "The owner called the cops on you and got you under control until the police arrived!"

**Cheat Code name:** Paint-n-GetBusted
**Recommanded lengths:**
**Easy:** 600 seconds -> 60 seconds if discovered
**Normal:** 600 seconds -> 60 seconds if discovered
**Hard:** 600 seconds + Busted if caught ->Effect ends
**Chaos:** 600 seconds  + Busted if caught -> Effect ends

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
I've had a fair bit of time to think about this and I don't think invisible effects would really be good to implement in a good fashion.

Also, the code for Pay 'n' Sprays is a bit ... interesting. I think it is being handled by a separate script, though I'm not sure.

Gonna close this for now.
