### ISSUE TITLE
[New Effect] "Speed" or Boom!

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#38]
Influenced by the 1994 movie "Speed" where a police officer had to save civilians from a speeding bus where, if it slowed down below 50mph, it would explode: https://en.wikipedia.org/wiki/Speed_(1994_film)

A bit of the same concept here: the effect would check for your speed (initial speed) when it starts. If you go under the initial speed, your car explodes. If you were immobile to begin with, you insta-boom. Very short effect.

**Cheat Code name:** NeedForConstantSpeed
**Recommanded lengths:**
**Easy:** 10 seconds
**Normal:** 15 seconds
**Hard:** 15 seconds
**Chaos:** 20 seconds

(Threads done as requested by Lordmau5)

**Comment by kruzgi** [comment]
+1 should be added

**Comment by Lordmau5** [comment]
Added in v3.0.1
