### ISSUE TITLE
[Fix] Game remembers on what radio channel you left it on

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#41]
Something in all GTA games is how the game randomly(?) decides what the radio station is when you get in a car. In chaos, it would be cool if you could set it once and then in each subsequent car you get in, it would be the same radio. Would be useful if you only want to listen to "User Tracks".

:)

**Comment by Lordmau5** [comment]
Decided that the Chaos Mod is not supposed to have such a feature as it's... well, yeah, not really fitting.
