### ISSUE TITLE
The mod or game?

### ISSUE THREAD

**Issue by robert375** [gta-chaos-mod/Trilogy-ASI-Script#59]
Followed the instructions for installing the mod and the game does unable to start correctly(0xc000007b) problem after help pls and its from steam.

**Comment by robert375** [comment]
someone help pls

**Comment by Lordmau5** [comment]
I completely forgot about this - I thought I already responded, sorry D:

Anyway. Is this issue still present?
Which game are you trying this on? SA, VC or 3?
Do you perhaps have SA:MP or MTA installed?
