### ISSUE TITLE
[New Effect] Randomly change the players vehicle

### ISSUE THREAD

**Issue by Chronophylos** [gta-chaos-mod/Trilogy-ASI-Script#6]
If the player doesn't have one just give one to him

**Comment by Lordmau5** [comment]
I'm actually unsure if it's possible to change the player's vehicle... It was brought up a few times already but I don't know if it's as easy as "change the model of the player's vehicle" or "create a vehicle and set the player's vehicle to that one" :/

**Comment by Lordmau5** [comment]
Tried somethign with the help of Parik but it ended up crashing and we weren't able to properly implement it sadly...
