### ISSUE TITLE
New camera effects

### ISSUE THREAD

**Issue by Ezneh** [gta-chaos-mod/Trilogy-ASI-Script#64]
Hey, I wanted to give you new ideas for camera effects (I had thought about them for a bit)
- inverted camera (horizontal)
- upside down camera (vertical)
- both (upside down and inverted)
- camera rotation: 90 / 270
- rotating camera (the camera just turns slowly to the left or right)

**Comment by Lordmau5** [comment]
Camera rotation and rotating camera isn't really possible from what I know.

If it is, then it's now on lower priority and might be revisited at a later point.

The rest is implemented though :)
