### ISSUE TITLE
my game keeps automatically crashes once i replace all the files?

### ISSUE THREAD

**Issue by thegithubuser1** [gta-chaos-mod/Trilogy-ASI-Script#72]

**Comment by Lordmau5** [comment]
- Did you make sure you are on v1.0 of the game? (It has to be v1.0, not 1.1, not 2.0, not 3.0, otherwise it won't work)
- Did you make sure you have a **clean** GTA:SA install? (No SA:MP or MTA installed into it)
- Which other mods do you have installed?
