### ISSUE TITLE
Application cannot see game when running via proton/wine

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [gta-chaos-mod/Trilogy-ASI-Script#76]
So I am sure none of this is probably something you imagined someone doing or planned on supporting. 

But I took to getting GTA:SA working on Ubuntu 19.10 via Lutris/Proton.
The Game works. 
Chaos mod app (With some coaxing) boots. 

Only problem is that ChaosMod doesn't see the running GTA, which I assume is because each is running in wine/proton.

As such the mod doesn't like to start properly.

I'm so close yet so far from achieving my goals of playing my favorite game on linux with my favorite mod. 

Like I said I am sure this is not something u intended, but any help would be nice.

**Comment by Parik27** [comment]
You have to install the .NET Framework using winetricks. You can't use mono or else it won't see it. I don't know how you'd do that with Proton, but it should be as simple as calling `winetricks dotnet472` on your prefix. You could also manually try to install using the .NET Redistributables, but I don't know how well that'd work.

**Comment by Lordmau5** [comment]
Seeing as this was answered back in the mid of May, and there's no response ever since, I'll assume this issue has been resolved.

If, however, this is still happening, don't hesitate to reply and I'll be happy to reopen it again :)
