### ISSUE TITLE
"Multiplayer" tab

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/Trilogy-ASI-Script#77]
What does the "Multiplayer" tab mean? How do I use it?
![Multiplayer](https://user-images.githubusercontent.com/63610557/82120747-c2af0400-97a1-11ea-84f4-f90df8c5dbd7.PNG)

**Comment by Lordmau5** [comment]
It's explained over here https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/tree/master/MultiplayerServer.NodeJS

**Comment by JustTunerYT** [comment]
> It's explained over here https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/tree/master/MultiplayerServer.NodeJS

Thank you!
