### ISSUE TITLE
I cannot open the "GTA Trilogy Chaos Mod.exe"

### ISSUE THREAD

**Issue by Valps** [gta-chaos-mod/Trilogy-ASI-Script#78]
Nothing happens after execute the program. I can't setup the cheats without this exe. I have tried execute in admin mode and Windows 7/8/XP compatibility mode. I use Windows 10.

**Comment by Lordmau5** [comment]
Did you make sure that you have .NET Framework 4.7.2 installed?
https://dotnet.microsoft.com/download/dotnet-framework/net472

**Comment by Valps** [comment]
I looked at the past issue and tried to install .NET Framework 4.7.2, but it gives an error stating that "This operating system is not supported". If I'm not mistaken, the framework installer should only be installed on older OSs, like W7, W vista etc. But I use Windows 10.

**Comment by Lordmau5** [comment]
If you are on Windows 10 then I don't see why the program shouldn't start.

Do you have any antivirus or other program installed that could prevent it from launching?
Windows Defender likes to just prevent it, so there's that.

**Comment by Valps** [comment]
I just disabled my antivirus and windows defender was already disabled. The program still does not open.

**Comment by Lordmau5** [comment]
Honestly have no idea as to why it wouldn't work.

You sadly seem to be the only one that's got this issue so it's way more difficult to track down.

Being on Windows 10 does help because I am not supporting anything that ... well, isn't Windows 10 at this point.

I'll leave this issue open in case someone else *did* have a similar problem and was able to find a solution they'd like to share, or if you ever manage to solve it yourself.

**Comment by Valps** [comment]
I solved the problem. I had a Windows 10 version 1607 (I have disabled windows update a few years ago). A one week ago, I updated the windows to 2004 version, but crashed my pc with infinites shutdowns on boot. Finally, Today I discovered that the problem was the died battery of notebook and a outdated bios from 2014. I reinstalled windows 10 version 2004 without boot errors, and now the GTA Trilogy Chaos Mod.exe works.

Thanks for your help!

**Comment by Lordmau5** [comment]
Interesting find...

I'll be adding that to the README in the next few days - thank you for responding to this issue again! 😁

**Comment by Stiffa1** [comment]
It does not work, I tried everything and updated the system, reinstalled version 1.0 more than 10 times
, the mod is running in the game 0 reactions

**Comment by Lordmau5** [comment]
> It does not work, I tried everything and updated the system, reinstalled version 1.0 more than 10 times , the mod is running in the game 0 reactions

Please open a new issue instead of replying to an old, already closed one.

Plus, more details in that - such as if you have GTA open, does it show the cooldown bar at the top? And if you have the pause menu open, if you hold F7, does it show the Chaos Mod version in the bottom left of the screen?
