### ISSUE TITLE
[New Effect] Make Love, Not War

### ISSUE THREAD

**Issue by MartyChonks** [gta-chaos-mod/Trilogy-ASI-Script#79]
Replace and restrict weapons for the player and peds to flowers and "toys" for the duration. Perhaps also put CJ in the gimp outfit for the duration.

**Recommended Sound on Effect Trigger:** [Rick James - Super Freak](https://youtu.be/QYHxGBH6o4M?t=72)

**Cheat Name:** MakeLoveNotWar

**Recommended Duration:** 90-180 seconds

**Comment by Lordmau5** [comment]
There's already native cheat "Kinky Theme" in the game as an effect so I don't see why we would need another one that is very similar to that.
