### ISSUE TITLE
Rename/rework "Faster Clock"

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#82]
So, as I am watching Lordmau5's VOD for his any% nmg chaos run this last weekend, there's something that made me think: the effect "Faster Clock". Now, there's is nothing wrong with the effect per se. It's just that the name is confusing. By its name, you'd assume that instead of going 1sec = 1min in-game clock, it would just go a bit faster (maybe 1sec = 10min in-game clock). But, instead, it goes _really_ fast (at least an hour a second).

So, in this light, either we change the name to something more descriptive of its speed, or change how it works by introducing tiers. Introducing tiers would be much mroe work than changing its name though. I suggest "Crazy Clock" or "Insane Clock".

Cheers.

**Comment by Lordmau5** [comment]
It is called "Faster Clock" because it's a cheat in the base game and literally every single cheat website calls it like that.
