### ISSUE TITLE
Multiplayer issue

### ISSUE THREAD

**Issue by RedNinjaBR** [gta-chaos-mod/Trilogy-ASI-Script#83]
I want to play with my brother whit 2 player mod, but , the player 2 can´t drive, only as ped

**Comment by Lordmau5** [comment]
The Multiplayer feature isn't what you think it is.

It's only allowing effects to be shared and activated at the same time (useful for when you are using Twitch voting, for example, so you can do that with multiple people)

**Comment by RedNinjaBR** [comment]
i was talking with a 2 player mod, but if don´t have a solution, ok, but i know what is the multiplayer twith vote, i only need to play with my brother with he not bugging
