### ISSUE TITLE
["New" Effect] «Anarchy Mode» Effect

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#84]
Remembering Lordmau5's work on the mod the other day, I came up with this idea for an effect: making "Anarchy Mode" an effect. Here's my idea on how it'll work because it depends wheter or not the mod is connected to Twitch chat or not.

**If it's not connected to Twitch chat:**
Timer starts at 45 seconds. Every 3 seconds, for 30 seconds, the game will select a random effect for a total of 10 random effects from the effect list (from all the other effects, regardless of what the player selected) that last 15 seconds each. The last 15 seconds are there to make the last effect time out.

**If connected to Twitch chat:**
Time starts at 15 seconds. Any cheats typed in chat are activated on the spot for 15 seconds. Only Rapid-Fire cheats can be activated.

Rapid-Fire can STILL happen after Anarchy, making this "effect" potentially very evil for Twitch players. For offline players, this can be a way to experience Rapid-Fire offline. Also, the effect cannot choose itself, for obvious reasons.

**Easy:** 45 seconds / 15 seconds
**Normal:** 45 seconds / 15 seconds
**Hard:** 45 seconds / 15 seconds
**Chaos:** 45 seconds / 15 seconds

**Comment by Lordmau5** [comment]
Added in v3.0.1 as:
- Rapid-Fire - 5 effects over the span of 10 seconds
- Hyper Rapid-Fire - 20 effects over the span of 10 seconds
- LIDL Rapid-Fire - 1 effect with a drum-roll
