### ISSUE TITLE
[Feature] Youtube Live Support

### ISSUE THREAD

**Issue by danylopez123** [gta-chaos-mod/Trilogy-ASI-Script#85]
I haven't tried this mod yet but i was reading the Readme section bellow and i saw it has a Twich support but no Youtube support wich is where i do my Streams

Is it possible to implement a Youtube Live support for it?

**Comment by Lordmau5** [comment]
It most certainly is possible but YouTube has an awful API that I don't want to touch.

If someone else would like to work on YouTube support I'm more than happy to accept pull requests for that.
