### ISSUE TITLE
Broken mirrored world effect

### ISSUE THREAD

**Issue by bozata** [gta-chaos-mod/Trilogy-ASI-Script#91]
When i get the mirrored world effect eveything just goes blue and i can't see absolutely anything

**Comment by Lordmau5** [comment]
Do you by any chance have an AMD graphics card?

If so, then there's the issue.

AMD graphics cards are not supported for that effect as nobody knows how to get it working on that.

Though, the mod is open source, so if someone that knows how to potentially get it working with GTA:SA then I'd be more than happy to accept a pull request for it a fix.

**Comment by bozata** [comment]
> Do you by any chance have an AMD graphics card?
> 
> If so, then there's the issue.
> 
> AMD graphics cards are not supported for that effect as nobody knows how to get it working on that.
> 
> Though, the mod is open source, so if someone that knows how to potentially get it working with GTA:SA then I'd be more than happy to accept a pull request for it a fix.

no i don't have an AMD, I have an Intel HD Graphics paired with an Intel Celeron B830

**Comment by NeX3s** [comment]
Same problem, Intel HD Graphics, Mirrored World, Mirrored Screen, Upside Down screen are all not working

**Comment by Lordmau5** [comment]
In that case integrated graphics are also not supported.
