### ISSUE TITLE
Stretched out Camera killing votes

### ISSUE THREAD

**Issue by zerogott** [gta-chaos-mod/Trilogy-ASI-Script#94]
Hey Lord,
seems like Votes break (atleast one vote) if the camera gets streched out before the vote starts.
Happend 2 times in Hams stream today.
One time he was send to heaven,the other time the cinematic camera from a stuntjump broke it.
The votes after the Camera was normal worked fine again.

**Comment by Lordmau5** [comment]
Do you have a clip or timestapm to where this happened?

I wouldn't put it past Twitch having hiccups. Can happen all the time, nothing I can do about it. (Hence why there's a "Poll failed" fallback)

**Comment by zerogott** [comment]
https://www.twitch.tv/videos/723895001?t=4h28m30s
The first vote that started before the cam got streched out still worked,the one that started midair broke for 99% of the people.
3 People only got to vote.
I sadly cant find the other one where the same happend with send to heaven,but with send to heaven nobody was able to vote,not even with reloading the page. We had to wait until ham hit the ground again and for a new vote to start voting again.

**Comment by Lordmau5** [comment]
From what I can tell that has nothing to do with the Chaos Mod itself, since votes were still coming through.

I am 99% sure this is purely a case of "correlation does not imply causation".
