### ISSUE TITLE
[New Effect] Reverse HESOYAM 

### ISSUE THREAD

**Issue by ShArCaDe** [gta-chaos-mod/Trilogy-ASI-Script#97]
When this is activated, the player's health, armor and money will be reduced. Maybe have the health and armor be reduced by 25% and the money by $250,000. The vehicle the player is in may also be damaged by 25%. If the player's health is less than 25%, the player will die.

Cheat name: MAYOSEH/INeedSomeHindrance

**Comment by Lordmau5** [comment]
Added in v3.0.1
